### ISSUE TITLE
Want to contribute...

### ISSUE THREAD

**Issue by jagannathhari** [thepratham81/video_processing_utility#2]
![2024-10-15_02 07 54_screenshot](https://github.com/user-attachments/assets/0d7ac57a-cda4-4423-950a-c8923d570926)
I would like to contribute to this project. I have implemented the GUI, and it's working to some extent.

**Comment by thepratham81** [comment]
Hey Jagganath Happy to work with you in this project too :)
I have sent you the collaborator invitation, please accept.
