### ISSUE TITLE
MPV is ready.

### ISSUE THREAD

**Issue by jagannathhari** [thepratham81/video_processing_utility#3]
![2024-10-28_10 16 29_screenshot](https://github.com/user-attachments/assets/e3ef757a-b2f4-46ba-bd99-6962c9e23ce0)
MPV is ready and functioning as expected. Would it be possible to make the mpv branch the main branch?

**Comment by thepratham81** [comment]
@Science2Technology @jagannathhari It's very nice to see the MVP is done, however I would suggest using Python instead which I believe is easily maintainable and have great library support.

**Comment by jagannathhari** [comment]
@thepratham81  , I will rewrite it in python.

**Comment by thepratham81** [comment]
@jagannathhari Please connect with me and work together. My WhatsApp number is +61 451939881
